#!/usr/bin/env node
/**
 * Portal OS — Icon Generator
 * Generates icon.png, icon.ico, icon.icns from the source SVG.
 *
 * Outputs:
 *   resources/icon.png   (512x512, used for Linux + BrowserWindow)
 *   resources/icon.ico   (multi-size, Windows installer + exe)
 *   resources/icon.icns  (macOS bundle — generated on macOS only)
 *   resources/icons/     (multi-size PNG directory for Linux AppImage)
 *
 * Built by JohannesAFK (StudoX)
 */

const sharp = require('sharp')
const pngToIco = require('png-to-ico').default
const fs = require('fs')
const path = require('path')

const resourcesDir = path.join(__dirname, '..', 'resources')
const iconsDir = path.join(resourcesDir, 'icons')

// Ensure output directory exists
fs.mkdirSync(iconsDir, { recursive: true })

// Portal OS icon — hexagon glyph on dark background with violet accent
const SIZE = 1024
const svgMarkup = `
<svg xmlns="http://www.w3.org/2000/svg" width="${SIZE}" height="${SIZE}" viewBox="0 0 ${SIZE} ${SIZE}">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#0d0d0d"/>
      <stop offset="100%" stop-color="#050505"/>
    </linearGradient>
    <linearGradient id="accent" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#9585f9"/>
      <stop offset="100%" stop-color="#7c6af7"/>
    </linearGradient>
  </defs>
  <rect width="${SIZE}" height="${SIZE}" rx="${SIZE * 0.21}" ry="${SIZE * 0.21}" fill="url(#bg)"/>
  <rect x="6" y="6" width="${SIZE - 12}" height="${SIZE - 12}" rx="${SIZE * 0.205}" ry="${SIZE * 0.205}" fill="none" stroke="rgba(255,255,255,0.06)" stroke-width="3"/>
  <polygon
    points="${SIZE / 2},${SIZE * 0.2} ${SIZE * 0.79},${SIZE * 0.33} ${SIZE * 0.79},${SIZE * 0.67} ${SIZE / 2},${SIZE * 0.8} ${SIZE * 0.21},${SIZE * 0.67} ${SIZE * 0.21},${SIZE * 0.33}"
    fill="none"
    stroke="url(#accent)"
    stroke-width="${SIZE * 0.028}"
    stroke-linejoin="round"
  />
  <circle cx="${SIZE / 2}" cy="${SIZE / 2}" r="${SIZE * 0.055}" fill="url(#accent)" opacity="0.85"/>
</svg>
`

async function main() {
  console.log('⬡ Portal OS — Icon Generator')
  console.log('─'.repeat(50))

  const svgBuffer = Buffer.from(svgMarkup)

  // 1. Generate base 512x512 PNG
  const mainPng = path.join(resourcesDir, 'icon.png')
  await sharp(svgBuffer).resize(512, 512).png().toFile(mainPng)
  console.log('✓ resources/icon.png (512x512)')

  // 2. Generate multi-size PNG set for Linux AppImage
  const sizes = [16, 24, 32, 48, 64, 96, 128, 256, 512, 1024]
  for (const size of sizes) {
    const out = path.join(iconsDir, `${size}x${size}.png`)
    await sharp(svgBuffer).resize(size, size).png().toFile(out)
    console.log(`✓ resources/icons/${size}x${size}.png`)
  }

  // 3. Generate Windows ICO (multi-size embedded)
  const icoSizes = [16, 24, 32, 48, 64, 128, 256]
  const icoBuffers = await Promise.all(
    icoSizes.map((size) =>
      sharp(svgBuffer).resize(size, size).png().toBuffer()
    )
  )
  const icoBuffer = await pngToIco(icoBuffers)
  const icoPath = path.join(resourcesDir, 'icon.ico')
  fs.writeFileSync(icoPath, icoBuffer)
  console.log('✓ resources/icon.ico (16,24,32,48,64,128,256)')

  // 4. ICNS note — requires macOS iconutil or png2icns
  const icnsPath = path.join(resourcesDir, 'icon.icns')
  if (!fs.existsSync(icnsPath)) {
    // Use png2icns from the iconset if available, otherwise leave placeholder
    try {
      const { execSync } = require('child_process')
      // Try iconutil (macOS only)
      if (process.platform === 'darwin') {
        const iconsetDir = path.join(resourcesDir, 'icon.iconset')
        fs.mkdirSync(iconsetDir, { recursive: true })
        const macSizes = [
          [16, '16x16'], [32, '16x16@2x'],
          [32, '32x32'], [64, '32x32@2x'],
          [128, '128x128'], [256, '128x128@2x'],
          [256, '256x256'], [512, '256x256@2x'],
          [512, '512x512'], [1024, '512x512@2x']
        ]
        for (const [px, name] of macSizes) {
          await sharp(svgBuffer).resize(px, px).png().toFile(path.join(iconsetDir, `icon_${name}.png`))
        }
        execSync(`iconutil -c icns -o "${icnsPath}" "${iconsetDir}"`)
        console.log('✓ resources/icon.icns (macOS)')
      } else {
        // Cross-platform fallback: copy 1024 PNG as .icns placeholder
        // Real ICNS will be generated by macOS CI runner
        await sharp(svgBuffer).resize(1024, 1024).png().toFile(icnsPath)
        console.log('✓ resources/icon.icns (PNG placeholder — real ICNS built on macOS runner)')
      }
    } catch (e) {
      await sharp(svgBuffer).resize(1024, 1024).png().toFile(icnsPath)
      console.log('✓ resources/icon.icns (PNG placeholder)')
    }
  }

  console.log('─'.repeat(50))
  console.log('Done.')
}

main().catch((err) => {
  console.error('Icon generation failed:', err)
  process.exit(1)
})
